# Generated by Django 5.2 on 2025-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Stationery Store', max_length=200)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_hint', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload the store logo (optional).', null=True, upload_to='store_logos/')),
            ],
            options={
                'verbose_name': 'Store Detail',
                'verbose_name_plural': 'Store Details',
            },
        ),
    ]
