# Generated by Django 5.2 on 2025-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_hint',
            field=models.CharField(blank=True, help_text='E.g., Landmark, Floor, Apartment number', max_length=255, null=True, verbose_name='Address Hint'),
        ),
    ]
