# Generated by Django 5.2 on 2025-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(blank=True, default='+91', max_length=5, null=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number (Local Part)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='school_grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Class'),
        ),
    ]
