# Generated by Django 5.2 on 2025-04-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_address_remove_customer_address_hint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='location_tags',
            field=models.ManyToManyField(blank=True, help_text="Tags describing the customer's location (e.g., Near School Gate, Block A)", related_name='customers', to='customers.locationtag'),
        ),
    ]
