# Generated by Django 5.2 on 2025-04-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_locationtag_customer_location_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_tags',
        ),
        migrations.AddField(
            model_name='address',
            name='location_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags describing this specific address location.', related_name='addresses', to='customers.locationtag'),
        ),
    ]
